### ISSUE TITLE
Parse error, am I doing this correctly?

### ISSUE THREAD

**Issue by CeIest** [Atemu/bookwalker-dl#10]
Hello there, when I try to run the script, I've got this [error](https://imgur.com/a/bzoS6Tc), do you know where I got it wrong? Needless to say I have all the dependencies installed. The BW ID is also from [a trial link](https://viewer-trial.bookwalker.jp/03/8/viewer.html?cid=3bd1e311-ba95-45dd-a7b3-e6256fa37892&cty=2).
Thanks!

**Comment by Atemu** [comment]
I missed one variable during refactoring and it worked despite that on my machine somehow, thanks for reporting!

After fixing this I found another bug with Manga, so that should work properly now.

I tested this with your Nisekoi chapter and a few other random Manga off the BW frontpage. Please let me know if you find a book that doesn't work.
